#pragma once
#pragma once
#include "httplib.h"
#include "d3d11.h"
#include "ImGui/imgui.h"
#include "ImGui/imgui_impl_dx11.h"
#include "ImGui/imgui_impl_win32.h"
#include <Windows.h>
#include <filesystem>
#include <nlohmann/json.hpp>
#include <iostream>
#include <string>
#include <map>
#include <vector>
#include <list>
#include <mutex>
#include <shared_mutex>
#include <sstream>
#include <thread>
#include <optional>
#include <atomic>
#include <csignal>
#include <Psapi.h>
#include <future>
#include <ctime>